# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1alpha1_validating_admission_policy_spec import V1alpha1ValidatingAdmissionPolicySpec

class TestV1alpha1ValidatingAdmissionPolicySpec(unittest.TestCase):
    """V1alpha1ValidatingAdmissionPolicySpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1ValidatingAdmissionPolicySpec:
        """Test V1alpha1ValidatingAdmissionPolicySpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1ValidatingAdmissionPolicySpec`
        """
        model = V1alpha1ValidatingAdmissionPolicySpec()
        if include_optional:
            return V1alpha1ValidatingAdmissionPolicySpec(
                audit_annotations = [
                    null
                    ],
                failure_policy = '',
                match_conditions = [
                    null
                    ],
                match_constraints = kubernetes_asyncio.models.v1alpha1/match_resources.v1alpha1.MatchResources(
                    exclude_resource_rules = [
                        null
                        ], 
                    match_policy = '', 
                    namespace_selector = null, 
                    object_selector = null, 
                    resource_rules = [
                        null
                        ], ),
                param_kind = kubernetes_asyncio.models.v1alpha1/param_kind.v1alpha1.ParamKind(
                    api_version = '', 
                    kind = '', ),
                validations = [
                    null
                    ],
                variables = [
                    null
                    ]
            )
        else:
            return V1alpha1ValidatingAdmissionPolicySpec(
        )
        """

    def testV1alpha1ValidatingAdmissionPolicySpec(self):
        """Test V1alpha1ValidatingAdmissionPolicySpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
