# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.api.core_api import CoreApi


class TestCoreApi(unittest.IsolatedAsyncioTestCase):
    """CoreApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CoreApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_api_versions(self) -> None:
        """Test case for get_api_versions

        """
        pass


if __name__ == '__main__':
    unittest.main()
