# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1beta1_mutation import V1beta1Mutation

class TestV1beta1Mutation(unittest.TestCase):
    """V1beta1Mutation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1Mutation:
        """Test V1beta1Mutation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1Mutation`
        """
        model = V1beta1Mutation()
        if include_optional:
            return V1beta1Mutation(
                apply_configuration = kubernetes_asyncio.models.v1beta1/apply_configuration.v1beta1.ApplyConfiguration(
                    expression = '', ),
                json_patch = kubernetes_asyncio.models.v1beta1/json_patch.v1beta1.JSONPatch(
                    expression = '', ),
                patch_type = ''
            )
        else:
            return V1beta1Mutation(
                patch_type = '',
        )
        """

    def testV1beta1Mutation(self):
        """Test V1beta1Mutation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
