# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.models.v1alpha3_device_taint_selector import V1alpha3DeviceTaintSelector

class TestV1alpha3DeviceTaintSelector(unittest.TestCase):
    """V1alpha3DeviceTaintSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha3DeviceTaintSelector:
        """Test V1alpha3DeviceTaintSelector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha3DeviceTaintSelector`
        """
        model = V1alpha3DeviceTaintSelector()
        if include_optional:
            return V1alpha3DeviceTaintSelector(
                device = '',
                device_class_name = '',
                driver = '',
                pool = '',
                selectors = [
                    kubernetes_asyncio.client.models.v1alpha3/device_selector.v1alpha3.DeviceSelector(
                        cel = kubernetes_asyncio.client.models.v1alpha3/cel_device_selector.v1alpha3.CELDeviceSelector(
                            expression = '', ), )
                    ]
            )
        else:
            return V1alpha3DeviceTaintSelector(
        )
        """

    def testV1alpha3DeviceTaintSelector(self):
        """Test V1alpha3DeviceTaintSelector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
