# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_network_policy_egress_rule import V1NetworkPolicyEgressRule

class TestV1NetworkPolicyEgressRule(unittest.TestCase):
    """V1NetworkPolicyEgressRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1NetworkPolicyEgressRule:
        """Test V1NetworkPolicyEgressRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1NetworkPolicyEgressRule`
        """
        model = V1NetworkPolicyEgressRule()
        if include_optional:
            return V1NetworkPolicyEgressRule(
                ports = [
                    null
                    ],
                to = [
                    null
                    ]
            )
        else:
            return V1NetworkPolicyEgressRule(
        )
        """

    def testV1NetworkPolicyEgressRule(self):
        """Test V1NetworkPolicyEgressRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
