# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_custom_resource_conversion import V1CustomResourceConversion

class TestV1CustomResourceConversion(unittest.TestCase):
    """V1CustomResourceConversion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CustomResourceConversion:
        """Test V1CustomResourceConversion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CustomResourceConversion`
        """
        model = V1CustomResourceConversion()
        if include_optional:
            return V1CustomResourceConversion(
                strategy = '',
                webhook = kubernetes_asyncio_pydantic.models.v1/webhook_conversion.v1.WebhookConversion(
                    client_config = null, 
                    conversion_review_versions = [
                        ''
                        ], )
            )
        else:
            return V1CustomResourceConversion(
                strategy = '',
        )
        """

    def testV1CustomResourceConversion(self):
        """Test V1CustomResourceConversion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
