# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v2_horizontal_pod_autoscaler_spec import V2HorizontalPodAutoscalerSpec

class TestV2HorizontalPodAutoscalerSpec(unittest.TestCase):
    """V2HorizontalPodAutoscalerSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2HorizontalPodAutoscalerSpec:
        """Test V2HorizontalPodAutoscalerSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2HorizontalPodAutoscalerSpec`
        """
        model = V2HorizontalPodAutoscalerSpec()
        if include_optional:
            return V2HorizontalPodAutoscalerSpec(
                behavior = kubernetes_asyncio_pydantic.models.v2/horizontal_pod_autoscaler_behavior.v2.HorizontalPodAutoscalerBehavior(
                    scale_down = null, 
                    scale_up = null, ),
                max_replicas = 56,
                metrics = [
                    null
                    ],
                min_replicas = 56,
                scale_target_ref = kubernetes_asyncio_pydantic.models.v2/cross_version_object_reference.v2.CrossVersionObjectReference(
                    api_version = '', 
                    kind = '', 
                    name = '', )
            )
        else:
            return V2HorizontalPodAutoscalerSpec(
                max_replicas = 56,
                scale_target_ref = kubernetes_asyncio_pydantic.models.v2/cross_version_object_reference.v2.CrossVersionObjectReference(
                    api_version = '', 
                    kind = '', 
                    name = '', ),
        )
        """

    def testV2HorizontalPodAutoscalerSpec(self):
        """Test V2HorizontalPodAutoscalerSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
