# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_container_restart_rule import V1ContainerRestartRule

class TestV1ContainerRestartRule(unittest.TestCase):
    """V1ContainerRestartRule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ContainerRestartRule:
        """Test V1ContainerRestartRule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ContainerRestartRule`
        """
        model = V1ContainerRestartRule()
        if include_optional:
            return V1ContainerRestartRule(
                action = '',
                exit_codes = kubernetes_asyncio_pydantic.models.v1/container_restart_rule_on_exit_codes.v1.ContainerRestartRuleOnExitCodes(
                    operator = '', 
                    values = [
                        56
                        ], )
            )
        else:
            return V1ContainerRestartRule(
                action = '',
        )
        """

    def testV1ContainerRestartRule(self):
        """Test V1ContainerRestartRule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
