# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.api.resource_v1alpha3_api import ResourceV1alpha3Api


class TestResourceV1alpha3Api(unittest.IsolatedAsyncioTestCase):
    """ResourceV1alpha3Api unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ResourceV1alpha3Api()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_device_taint_rule(self) -> None:
        """Test case for create_device_taint_rule

        """
        pass

    async def test_delete_collection_device_taint_rule(self) -> None:
        """Test case for delete_collection_device_taint_rule

        """
        pass

    async def test_delete_device_taint_rule(self) -> None:
        """Test case for delete_device_taint_rule

        """
        pass

    async def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    async def test_list_device_taint_rule(self) -> None:
        """Test case for list_device_taint_rule

        """
        pass

    async def test_patch_device_taint_rule(self) -> None:
        """Test case for patch_device_taint_rule

        """
        pass

    async def test_read_device_taint_rule(self) -> None:
        """Test case for read_device_taint_rule

        """
        pass

    async def test_replace_device_taint_rule(self) -> None:
        """Test case for replace_device_taint_rule

        """
        pass


if __name__ == '__main__':
    unittest.main()
