# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_rolling_update_daemon_set import V1RollingUpdateDaemonSet

class TestV1RollingUpdateDaemonSet(unittest.TestCase):
    """V1RollingUpdateDaemonSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1RollingUpdateDaemonSet:
        """Test V1RollingUpdateDaemonSet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1RollingUpdateDaemonSet`
        """
        model = V1RollingUpdateDaemonSet()
        if include_optional:
            return V1RollingUpdateDaemonSet(
                max_surge = None,
                max_unavailable = None
            )
        else:
            return V1RollingUpdateDaemonSet(
        )
        """

    def testV1RollingUpdateDaemonSet(self):
        """Test V1RollingUpdateDaemonSet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
