# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_ingress_backend import V1IngressBackend

class TestV1IngressBackend(unittest.TestCase):
    """V1IngressBackend unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1IngressBackend:
        """Test V1IngressBackend
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1IngressBackend`
        """
        model = V1IngressBackend()
        if include_optional:
            return V1IngressBackend(
                resource = kubernetes_asyncio.models.v1/typed_local_object_reference.v1.TypedLocalObjectReference(
                    api_group = '', 
                    kind = '', 
                    name = '', ),
                service = kubernetes_asyncio.models.v1/ingress_service_backend.v1.IngressServiceBackend(
                    name = '', 
                    port = null, )
            )
        else:
            return V1IngressBackend(
        )
        """

    def testV1IngressBackend(self):
        """Test V1IngressBackend"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
