# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1alpha2_named_resources_resources import V1alpha2NamedResourcesResources

class TestV1alpha2NamedResourcesResources(unittest.TestCase):
    """V1alpha2NamedResourcesResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha2NamedResourcesResources:
        """Test V1alpha2NamedResourcesResources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha2NamedResourcesResources`
        """
        model = V1alpha2NamedResourcesResources()
        if include_optional:
            return V1alpha2NamedResourcesResources(
                instances = [
                    null
                    ]
            )
        else:
            return V1alpha2NamedResourcesResources(
                instances = [
                    null
                    ],
        )
        """

    def testV1alpha2NamedResourcesResources(self):
        """Test V1alpha2NamedResourcesResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
