# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_replication_controller_spec import V1ReplicationControllerSpec

class TestV1ReplicationControllerSpec(unittest.TestCase):
    """V1ReplicationControllerSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ReplicationControllerSpec:
        """Test V1ReplicationControllerSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ReplicationControllerSpec`
        """
        model = V1ReplicationControllerSpec()
        if include_optional:
            return V1ReplicationControllerSpec(
                min_ready_seconds = 56,
                replicas = 56,
                selector = {
                    'key' : ''
                    },
                template = kubernetes_asyncio_pydantic.models.v1/pod_template_spec.v1.PodTemplateSpec(
                    metadata = null, 
                    spec = null, )
            )
        else:
            return V1ReplicationControllerSpec(
        )
        """

    def testV1ReplicationControllerSpec(self):
        """Test V1ReplicationControllerSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
