# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v2_pods_metric_source import V2PodsMetricSource

class TestV2PodsMetricSource(unittest.TestCase):
    """V2PodsMetricSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2PodsMetricSource:
        """Test V2PodsMetricSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2PodsMetricSource`
        """
        model = V2PodsMetricSource()
        if include_optional:
            return V2PodsMetricSource(
                metric = kubernetes_asyncio.models.v2/metric_identifier.v2.MetricIdentifier(
                    name = '', 
                    selector = null, ),
                target = kubernetes_asyncio.models.v2/metric_target.v2.MetricTarget(
                    average_utilization = 56, 
                    average_value = null, 
                    type = '', 
                    value = null, )
            )
        else:
            return V2PodsMetricSource(
                metric = kubernetes_asyncio.models.v2/metric_identifier.v2.MetricIdentifier(
                    name = '', 
                    selector = null, ),
                target = kubernetes_asyncio.models.v2/metric_target.v2.MetricTarget(
                    average_utilization = 56, 
                    average_value = null, 
                    type = '', 
                    value = null, ),
        )
        """

    def testV2PodsMetricSource(self):
        """Test V2PodsMetricSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
