# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_exact_device_request import V1ExactDeviceRequest

class TestV1ExactDeviceRequest(unittest.TestCase):
    """V1ExactDeviceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ExactDeviceRequest:
        """Test V1ExactDeviceRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ExactDeviceRequest`
        """
        model = V1ExactDeviceRequest()
        if include_optional:
            return V1ExactDeviceRequest(
                admin_access = True,
                allocation_mode = '',
                capacity = kubernetes_asyncio.models.v1/capacity_requirements.v1.CapacityRequirements(
                    requests = {
                        'key' : kubernetes_asyncio.models.v1_pod_spec_overhead_value.v1_PodSpec_overhead_value()
                        }, ),
                count = 56,
                device_class_name = '',
                selectors = [
                    null
                    ],
                tolerations = [
                    null
                    ]
            )
        else:
            return V1ExactDeviceRequest(
                device_class_name = '',
        )
        """

    def testV1ExactDeviceRequest(self):
        """Test V1ExactDeviceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
