# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_api_versions import V1APIVersions

class TestV1APIVersions(unittest.TestCase):
    """V1APIVersions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1APIVersions:
        """Test V1APIVersions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1APIVersions`
        """
        model = V1APIVersions()
        if include_optional:
            return V1APIVersions(
                api_version = '',
                kind = '',
                server_address_by_client_cidrs = [
                    null
                    ],
                versions = [
                    ''
                    ]
            )
        else:
            return V1APIVersions(
                server_address_by_client_cidrs = [
                    null
                    ],
                versions = [
                    ''
                    ],
        )
        """

    def testV1APIVersions(self):
        """Test V1APIVersions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
