# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_node_config_status import V1NodeConfigStatus

class TestV1NodeConfigStatus(unittest.TestCase):
    """V1NodeConfigStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1NodeConfigStatus:
        """Test V1NodeConfigStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1NodeConfigStatus`
        """
        model = V1NodeConfigStatus()
        if include_optional:
            return V1NodeConfigStatus(
                active = kubernetes_asyncio.models.v1/node_config_source.v1.NodeConfigSource(
                    config_map = null, ),
                assigned = kubernetes_asyncio.models.v1/node_config_source.v1.NodeConfigSource(
                    config_map = null, ),
                error = '',
                last_known_good = kubernetes_asyncio.models.v1/node_config_source.v1.NodeConfigSource(
                    config_map = null, )
            )
        else:
            return V1NodeConfigStatus(
        )
        """

    def testV1NodeConfigStatus(self):
        """Test V1NodeConfigStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
