# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1beta3_subject import V1beta3Subject

class TestV1beta3Subject(unittest.TestCase):
    """V1beta3Subject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta3Subject:
        """Test V1beta3Subject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta3Subject`
        """
        model = V1beta3Subject()
        if include_optional:
            return V1beta3Subject(
                group = kubernetes_asyncio.models.v1beta3/group_subject.v1beta3.GroupSubject(
                    name = '', ),
                kind = '',
                service_account = kubernetes_asyncio.models.v1beta3/service_account_subject.v1beta3.ServiceAccountSubject(
                    name = '', 
                    namespace = '', ),
                user = kubernetes_asyncio.models.v1beta3/user_subject.v1beta3.UserSubject(
                    name = '', )
            )
        else:
            return V1beta3Subject(
                kind = '',
        )
        """

    def testV1beta3Subject(self):
        """Test V1beta3Subject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
