# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_custom_resource_definition import V1CustomResourceDefinition

class TestV1CustomResourceDefinition(unittest.TestCase):
    """V1CustomResourceDefinition unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CustomResourceDefinition:
        """Test V1CustomResourceDefinition
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CustomResourceDefinition`
        """
        model = V1CustomResourceDefinition()
        if include_optional:
            return V1CustomResourceDefinition(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v1/custom_resource_definition_spec.v1.CustomResourceDefinitionSpec(
                    conversion = null, 
                    group = '', 
                    names = null, 
                    preserve_unknown_fields = True, 
                    scope = '', 
                    versions = [
                        null
                        ], ),
                status = kubernetes_asyncio.models.v1/custom_resource_definition_status.v1.CustomResourceDefinitionStatus(
                    accepted_names = null, 
                    conditions = [
                        null
                        ], 
                    stored_versions = [
                        ''
                        ], )
            )
        else:
            return V1CustomResourceDefinition(
                spec = kubernetes_asyncio.models.v1/custom_resource_definition_spec.v1.CustomResourceDefinitionSpec(
                    conversion = null, 
                    group = '', 
                    names = null, 
                    preserve_unknown_fields = True, 
                    scope = '', 
                    versions = [
                        null
                        ], ),
        )
        """

    def testV1CustomResourceDefinition(self):
        """Test V1CustomResourceDefinition"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
