# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_lifecycle import V1Lifecycle

class TestV1Lifecycle(unittest.TestCase):
    """V1Lifecycle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1Lifecycle:
        """Test V1Lifecycle
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1Lifecycle`
        """
        model = V1Lifecycle()
        if include_optional:
            return V1Lifecycle(
                post_start = kubernetes_asyncio_pydantic.models.v1/lifecycle_handler.v1.LifecycleHandler(
                    exec = null, 
                    http_get = null, 
                    sleep = null, 
                    tcp_socket = null, ),
                pre_stop = kubernetes_asyncio_pydantic.models.v1/lifecycle_handler.v1.LifecycleHandler(
                    exec = null, 
                    http_get = null, 
                    sleep = null, 
                    tcp_socket = null, )
            )
        else:
            return V1Lifecycle(
        )
        """

    def testV1Lifecycle(self):
        """Test V1Lifecycle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
