# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v2_metric_value_status import V2MetricValueStatus

class TestV2MetricValueStatus(unittest.TestCase):
    """V2MetricValueStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2MetricValueStatus:
        """Test V2MetricValueStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2MetricValueStatus`
        """
        model = V2MetricValueStatus()
        if include_optional:
            return V2MetricValueStatus(
                average_utilization = 56,
                average_value = None,
                value = None
            )
        else:
            return V2MetricValueStatus(
        )
        """

    def testV2MetricValueStatus(self):
        """Test V2MetricValueStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
