# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_csi_storage_capacity_maximum_volume_size import V1CSIStorageCapacityMaximumVolumeSize

class TestV1CSIStorageCapacityMaximumVolumeSize(unittest.TestCase):
    """V1CSIStorageCapacityMaximumVolumeSize unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CSIStorageCapacityMaximumVolumeSize:
        """Test V1CSIStorageCapacityMaximumVolumeSize
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CSIStorageCapacityMaximumVolumeSize`
        """
        model = V1CSIStorageCapacityMaximumVolumeSize()
        if include_optional:
            return V1CSIStorageCapacityMaximumVolumeSize(
            )
        else:
            return V1CSIStorageCapacityMaximumVolumeSize(
        )
        """

    def testV1CSIStorageCapacityMaximumVolumeSize(self):
        """Test V1CSIStorageCapacityMaximumVolumeSize"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
