# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_volume_node_affinity import V1VolumeNodeAffinity

class TestV1VolumeNodeAffinity(unittest.TestCase):
    """V1VolumeNodeAffinity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1VolumeNodeAffinity:
        """Test V1VolumeNodeAffinity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1VolumeNodeAffinity`
        """
        model = V1VolumeNodeAffinity()
        if include_optional:
            return V1VolumeNodeAffinity(
                required = kubernetes_asyncio.models.v1/node_selector.v1.NodeSelector(
                    node_selector_terms = [
                        null
                        ], )
            )
        else:
            return V1VolumeNodeAffinity(
        )
        """

    def testV1VolumeNodeAffinity(self):
        """Test V1VolumeNodeAffinity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
