# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_resource_field_selector_divisor import V1ResourceFieldSelectorDivisor

class TestV1ResourceFieldSelectorDivisor(unittest.TestCase):
    """V1ResourceFieldSelectorDivisor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ResourceFieldSelectorDivisor:
        """Test V1ResourceFieldSelectorDivisor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ResourceFieldSelectorDivisor`
        """
        model = V1ResourceFieldSelectorDivisor()
        if include_optional:
            return V1ResourceFieldSelectorDivisor(
            )
        else:
            return V1ResourceFieldSelectorDivisor(
        )
        """

    def testV1ResourceFieldSelectorDivisor(self):
        """Test V1ResourceFieldSelectorDivisor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
