# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1alpha3_resource_claim import V1alpha3ResourceClaim

class TestV1alpha3ResourceClaim(unittest.TestCase):
    """V1alpha3ResourceClaim unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha3ResourceClaim:
        """Test V1alpha3ResourceClaim
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha3ResourceClaim`
        """
        model = V1alpha3ResourceClaim()
        if include_optional:
            return V1alpha3ResourceClaim(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v1alpha3/resource_claim_spec.v1alpha3.ResourceClaimSpec(
                    controller = '', 
                    devices = null, ),
                status = kubernetes_asyncio.models.v1alpha3/resource_claim_status.v1alpha3.ResourceClaimStatus(
                    allocation = null, 
                    deallocation_requested = True, 
                    reserved_for = [
                        null
                        ], )
            )
        else:
            return V1alpha3ResourceClaim(
                spec = kubernetes_asyncio.models.v1alpha3/resource_claim_spec.v1alpha3.ResourceClaimSpec(
                    controller = '', 
                    devices = null, ),
        )
        """

    def testV1alpha3ResourceClaim(self):
        """Test V1alpha3ResourceClaim"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
