# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1beta1_resource_claim_spec import V1beta1ResourceClaimSpec

class TestV1beta1ResourceClaimSpec(unittest.TestCase):
    """V1beta1ResourceClaimSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1ResourceClaimSpec:
        """Test V1beta1ResourceClaimSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1ResourceClaimSpec`
        """
        model = V1beta1ResourceClaimSpec()
        if include_optional:
            return V1beta1ResourceClaimSpec(
                devices = kubernetes_asyncio.models.v1beta1/device_claim.v1beta1.DeviceClaim(
                    config = [
                        null
                        ], 
                    constraints = [
                        null
                        ], 
                    requests = [
                        null
                        ], )
            )
        else:
            return V1beta1ResourceClaimSpec(
        )
        """

    def testV1beta1ResourceClaimSpec(self):
        """Test V1beta1ResourceClaimSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
