# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1alpha2_resource_handle import V1alpha2ResourceHandle

class TestV1alpha2ResourceHandle(unittest.TestCase):
    """V1alpha2ResourceHandle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha2ResourceHandle:
        """Test V1alpha2ResourceHandle
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha2ResourceHandle`
        """
        model = V1alpha2ResourceHandle()
        if include_optional:
            return V1alpha2ResourceHandle(
                data = '',
                driver_name = '',
                structured_data = kubernetes_asyncio.models.v1alpha2/structured_resource_handle.v1alpha2.StructuredResourceHandle(
                    node_name = '', 
                    results = [
                        null
                        ], 
                    vendor_claim_parameters = null, 
                    vendor_class_parameters = null, )
            )
        else:
            return V1alpha2ResourceHandle(
        )
        """

    def testV1alpha2ResourceHandle(self):
        """Test V1alpha2ResourceHandle"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
