# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_network_policy import V1NetworkPolicy

class TestV1NetworkPolicy(unittest.TestCase):
    """V1NetworkPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1NetworkPolicy:
        """Test V1NetworkPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1NetworkPolicy`
        """
        model = V1NetworkPolicy()
        if include_optional:
            return V1NetworkPolicy(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio_pydantic.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio_pydantic.models.v1/network_policy_spec.v1.NetworkPolicySpec(
                    egress = [
                        null
                        ], 
                    ingress = [
                        null
                        ], 
                    pod_selector = null, 
                    policy_types = [
                        ''
                        ], )
            )
        else:
            return V1NetworkPolicy(
        )
        """

    def testV1NetworkPolicy(self):
        """Test V1NetworkPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
