# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_endpoints_list import V1EndpointsList

class TestV1EndpointsList(unittest.TestCase):
    """V1EndpointsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1EndpointsList:
        """Test V1EndpointsList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1EndpointsList`
        """
        model = V1EndpointsList()
        if include_optional:
            return V1EndpointsList(
                api_version = '',
                items = [
                    null
                    ],
                kind = '',
                metadata = kubernetes_asyncio_pydantic.models.v1/list_meta.v1.ListMeta(
                    continue = '', 
                    remaining_item_count = 56, 
                    resource_version = '', 
                    self_link = '', )
            )
        else:
            return V1EndpointsList(
                items = [
                    null
                    ],
        )
        """

    def testV1EndpointsList(self):
        """Test V1EndpointsList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
