# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_cron_job_spec import V1CronJobSpec

class TestV1CronJobSpec(unittest.TestCase):
    """V1CronJobSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CronJobSpec:
        """Test V1CronJobSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CronJobSpec`
        """
        model = V1CronJobSpec()
        if include_optional:
            return V1CronJobSpec(
                concurrency_policy = '',
                failed_jobs_history_limit = 56,
                job_template = kubernetes_asyncio.models.v1/job_template_spec.v1.JobTemplateSpec(
                    metadata = null, 
                    spec = null, ),
                schedule = '',
                starting_deadline_seconds = 56,
                successful_jobs_history_limit = 56,
                suspend = True,
                time_zone = ''
            )
        else:
            return V1CronJobSpec(
                job_template = kubernetes_asyncio.models.v1/job_template_spec.v1.JobTemplateSpec(
                    metadata = null, 
                    spec = null, ),
                schedule = '',
        )
        """

    def testV1CronJobSpec(self):
        """Test V1CronJobSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
