# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1beta2_resource_slice_spec import V1beta2ResourceSliceSpec

class TestV1beta2ResourceSliceSpec(unittest.TestCase):
    """V1beta2ResourceSliceSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta2ResourceSliceSpec:
        """Test V1beta2ResourceSliceSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta2ResourceSliceSpec`
        """
        model = V1beta2ResourceSliceSpec()
        if include_optional:
            return V1beta2ResourceSliceSpec(
                all_nodes = True,
                devices = [
                    null
                    ],
                driver = '',
                node_name = '',
                node_selector = kubernetes_asyncio_pydantic.models.v1/node_selector.v1.NodeSelector(
                    node_selector_terms = [
                        null
                        ], ),
                per_device_node_selection = True,
                pool = kubernetes_asyncio_pydantic.models.v1beta2/resource_pool.v1beta2.ResourcePool(
                    generation = 56, 
                    name = '', 
                    resource_slice_count = 56, ),
                shared_counters = [
                    null
                    ]
            )
        else:
            return V1beta2ResourceSliceSpec(
                driver = '',
                pool = kubernetes_asyncio_pydantic.models.v1beta2/resource_pool.v1beta2.ResourcePool(
                    generation = 56, 
                    name = '', 
                    resource_slice_count = 56, ),
        )
        """

    def testV1beta2ResourceSliceSpec(self):
        """Test V1beta2ResourceSliceSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
