# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_webhook_client_config1 import V1WebhookClientConfig1

class TestV1WebhookClientConfig1(unittest.TestCase):
    """V1WebhookClientConfig1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1WebhookClientConfig1:
        """Test V1WebhookClientConfig1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1WebhookClientConfig1`
        """
        model = V1WebhookClientConfig1()
        if include_optional:
            return V1WebhookClientConfig1(
                ca_bundle = 'YQ==',
                service = kubernetes_asyncio.models.v1/service_reference_1.v1.ServiceReference_1(
                    name = '', 
                    namespace = '', 
                    path = '', 
                    port = 56, ),
                url = ''
            )
        else:
            return V1WebhookClientConfig1(
        )
        """

    def testV1WebhookClientConfig1(self):
        """Test V1WebhookClientConfig1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
