# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1beta1_mutating_admission_policy_binding_spec import V1beta1MutatingAdmissionPolicyBindingSpec

class TestV1beta1MutatingAdmissionPolicyBindingSpec(unittest.TestCase):
    """V1beta1MutatingAdmissionPolicyBindingSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1MutatingAdmissionPolicyBindingSpec:
        """Test V1beta1MutatingAdmissionPolicyBindingSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1MutatingAdmissionPolicyBindingSpec`
        """
        model = V1beta1MutatingAdmissionPolicyBindingSpec()
        if include_optional:
            return V1beta1MutatingAdmissionPolicyBindingSpec(
                match_resources = kubernetes_asyncio.models.v1beta1/match_resources.v1beta1.MatchResources(
                    exclude_resource_rules = [
                        null
                        ], 
                    match_policy = '', 
                    namespace_selector = null, 
                    object_selector = null, 
                    resource_rules = [
                        null
                        ], ),
                param_ref = kubernetes_asyncio.models.v1beta1/param_ref.v1beta1.ParamRef(
                    name = '', 
                    namespace = '', 
                    parameter_not_found_action = '', 
                    selector = null, ),
                policy_name = ''
            )
        else:
            return V1beta1MutatingAdmissionPolicyBindingSpec(
        )
        """

    def testV1beta1MutatingAdmissionPolicyBindingSpec(self):
        """Test V1beta1MutatingAdmissionPolicyBindingSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
