# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_tcp_socket_action import V1TCPSocketAction

class TestV1TCPSocketAction(unittest.TestCase):
    """V1TCPSocketAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TCPSocketAction:
        """Test V1TCPSocketAction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TCPSocketAction`
        """
        model = V1TCPSocketAction()
        if include_optional:
            return V1TCPSocketAction(
                host = '',
                port = None
            )
        else:
            return V1TCPSocketAction(
                port = None,
        )
        """

    def testV1TCPSocketAction(self):
        """Test V1TCPSocketAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
