# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_pod_affinity import V1PodAffinity

class TestV1PodAffinity(unittest.TestCase):
    """V1PodAffinity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PodAffinity:
        """Test V1PodAffinity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PodAffinity`
        """
        model = V1PodAffinity()
        if include_optional:
            return V1PodAffinity(
                preferred_during_scheduling_ignored_during_execution = [
                    null
                    ],
                required_during_scheduling_ignored_during_execution = [
                    null
                    ]
            )
        else:
            return V1PodAffinity(
        )
        """

    def testV1PodAffinity(self):
        """Test V1PodAffinity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
