# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.models.v1beta1_device_taint import V1beta1DeviceTaint

class TestV1beta1DeviceTaint(unittest.TestCase):
    """V1beta1DeviceTaint unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1DeviceTaint:
        """Test V1beta1DeviceTaint
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1DeviceTaint`
        """
        model = V1beta1DeviceTaint()
        if include_optional:
            return V1beta1DeviceTaint(
                effect = '',
                key = '',
                time_added = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                value = ''
            )
        else:
            return V1beta1DeviceTaint(
                effect = '',
                key = '',
        )
        """

    def testV1beta1DeviceTaint(self):
        """Test V1beta1DeviceTaint"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
