# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_device_class_spec import V1DeviceClassSpec

class TestV1DeviceClassSpec(unittest.TestCase):
    """V1DeviceClassSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DeviceClassSpec:
        """Test V1DeviceClassSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DeviceClassSpec`
        """
        model = V1DeviceClassSpec()
        if include_optional:
            return V1DeviceClassSpec(
                config = [
                    null
                    ],
                extended_resource_name = '',
                selectors = [
                    null
                    ]
            )
        else:
            return V1DeviceClassSpec(
        )
        """

    def testV1DeviceClassSpec(self):
        """Test V1DeviceClassSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
