# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_cel_device_selector import V1CELDeviceSelector

class TestV1CELDeviceSelector(unittest.TestCase):
    """V1CELDeviceSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CELDeviceSelector:
        """Test V1CELDeviceSelector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CELDeviceSelector`
        """
        model = V1CELDeviceSelector()
        if include_optional:
            return V1CELDeviceSelector(
                expression = ''
            )
        else:
            return V1CELDeviceSelector(
                expression = '',
        )
        """

    def testV1CELDeviceSelector(self):
        """Test V1CELDeviceSelector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
