# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_api_resource_list import V1APIResourceList

class TestV1APIResourceList(unittest.TestCase):
    """V1APIResourceList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1APIResourceList:
        """Test V1APIResourceList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1APIResourceList`
        """
        model = V1APIResourceList()
        if include_optional:
            return V1APIResourceList(
                api_version = '',
                group_version = '',
                kind = '',
                resources = [
                    null
                    ]
            )
        else:
            return V1APIResourceList(
                group_version = '',
                resources = [
                    null
                    ],
        )
        """

    def testV1APIResourceList(self):
        """Test V1APIResourceList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
