# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.api.scheduling_v1_api import SchedulingV1Api


class TestSchedulingV1Api(unittest.IsolatedAsyncioTestCase):
    """SchedulingV1Api unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SchedulingV1Api()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_priority_class(self) -> None:
        """Test case for create_priority_class

        """
        pass

    async def test_delete_collection_priority_class(self) -> None:
        """Test case for delete_collection_priority_class

        """
        pass

    async def test_delete_priority_class(self) -> None:
        """Test case for delete_priority_class

        """
        pass

    async def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    async def test_list_priority_class(self) -> None:
        """Test case for list_priority_class

        """
        pass

    async def test_patch_priority_class(self) -> None:
        """Test case for patch_priority_class

        """
        pass

    async def test_read_priority_class(self) -> None:
        """Test case for read_priority_class

        """
        pass

    async def test_replace_priority_class(self) -> None:
        """Test case for replace_priority_class

        """
        pass


if __name__ == '__main__':
    unittest.main()
