# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1alpha3_pod_scheduling_context_status import V1alpha3PodSchedulingContextStatus

class TestV1alpha3PodSchedulingContextStatus(unittest.TestCase):
    """V1alpha3PodSchedulingContextStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha3PodSchedulingContextStatus:
        """Test V1alpha3PodSchedulingContextStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha3PodSchedulingContextStatus`
        """
        model = V1alpha3PodSchedulingContextStatus()
        if include_optional:
            return V1alpha3PodSchedulingContextStatus(
                resource_claims = [
                    null
                    ]
            )
        else:
            return V1alpha3PodSchedulingContextStatus(
        )
        """

    def testV1alpha3PodSchedulingContextStatus(self):
        """Test V1alpha3PodSchedulingContextStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
