# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_node_selector_term import V1NodeSelectorTerm

class TestV1NodeSelectorTerm(unittest.TestCase):
    """V1NodeSelectorTerm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1NodeSelectorTerm:
        """Test V1NodeSelectorTerm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1NodeSelectorTerm`
        """
        model = V1NodeSelectorTerm()
        if include_optional:
            return V1NodeSelectorTerm(
                match_expressions = [
                    null
                    ],
                match_fields = [
                    null
                    ]
            )
        else:
            return V1NodeSelectorTerm(
        )
        """

    def testV1NodeSelectorTerm(self):
        """Test V1NodeSelectorTerm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
