# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v2_horizontal_pod_autoscaler_list import V2HorizontalPodAutoscalerList

class TestV2HorizontalPodAutoscalerList(unittest.TestCase):
    """V2HorizontalPodAutoscalerList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2HorizontalPodAutoscalerList:
        """Test V2HorizontalPodAutoscalerList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2HorizontalPodAutoscalerList`
        """
        model = V2HorizontalPodAutoscalerList()
        if include_optional:
            return V2HorizontalPodAutoscalerList(
                api_version = '',
                items = [
                    null
                    ],
                kind = '',
                metadata = kubernetes_asyncio.models.v1/list_meta.v1.ListMeta(
                    continue = '', 
                    remaining_item_count = 56, 
                    resource_version = '', 
                    self_link = '', )
            )
        else:
            return V2HorizontalPodAutoscalerList(
                items = [
                    null
                    ],
        )
        """

    def testV2HorizontalPodAutoscalerList(self):
        """Test V2HorizontalPodAutoscalerList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
