# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_mutating_webhook import V1MutatingWebhook

class TestV1MutatingWebhook(unittest.TestCase):
    """V1MutatingWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1MutatingWebhook:
        """Test V1MutatingWebhook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1MutatingWebhook`
        """
        model = V1MutatingWebhook()
        if include_optional:
            return V1MutatingWebhook(
                admission_review_versions = [
                    ''
                    ],
                client_config = kubernetes_asyncio.models.v1/webhook_client_config.v1.WebhookClientConfig(
                    ca_bundle = 'YQ==', 
                    service = null, 
                    url = '', ),
                failure_policy = '',
                match_conditions = [
                    null
                    ],
                match_policy = '',
                name = '',
                namespace_selector = kubernetes_asyncio.models.v1/label_selector.v1.LabelSelector(
                    match_expressions = [
                        null
                        ], 
                    match_labels = {
                        'key' : ''
                        }, ),
                object_selector = kubernetes_asyncio.models.v1/label_selector.v1.LabelSelector(
                    match_expressions = [
                        null
                        ], 
                    match_labels = {
                        'key' : ''
                        }, ),
                reinvocation_policy = '',
                rules = [
                    null
                    ],
                side_effects = '',
                timeout_seconds = 56
            )
        else:
            return V1MutatingWebhook(
                admission_review_versions = [
                    ''
                    ],
                client_config = kubernetes_asyncio.models.v1/webhook_client_config.v1.WebhookClientConfig(
                    ca_bundle = 'YQ==', 
                    service = null, 
                    url = '', ),
                name = '',
                side_effects = '',
        )
        """

    def testV1MutatingWebhook(self):
        """Test V1MutatingWebhook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
