# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_opaque_device_configuration import V1OpaqueDeviceConfiguration

class TestV1OpaqueDeviceConfiguration(unittest.TestCase):
    """V1OpaqueDeviceConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1OpaqueDeviceConfiguration:
        """Test V1OpaqueDeviceConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1OpaqueDeviceConfiguration`
        """
        model = V1OpaqueDeviceConfiguration()
        if include_optional:
            return V1OpaqueDeviceConfiguration(
                driver = '',
                parameters = None
            )
        else:
            return V1OpaqueDeviceConfiguration(
                driver = '',
                parameters = None,
        )
        """

    def testV1OpaqueDeviceConfiguration(self):
        """Test V1OpaqueDeviceConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
