# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.api.openid_api import OpenidApi


class TestOpenidApi(unittest.IsolatedAsyncioTestCase):
    """OpenidApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = OpenidApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_service_account_issuer_open_id_keyset(self) -> None:
        """Test case for get_service_account_issuer_open_id_keyset

        """
        pass


if __name__ == '__main__':
    unittest.main()
