# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_policy_rules_with_subjects import V1PolicyRulesWithSubjects

class TestV1PolicyRulesWithSubjects(unittest.TestCase):
    """V1PolicyRulesWithSubjects unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PolicyRulesWithSubjects:
        """Test V1PolicyRulesWithSubjects
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PolicyRulesWithSubjects`
        """
        model = V1PolicyRulesWithSubjects()
        if include_optional:
            return V1PolicyRulesWithSubjects(
                non_resource_rules = [
                    null
                    ],
                resource_rules = [
                    null
                    ],
                subjects = [
                    null
                    ]
            )
        else:
            return V1PolicyRulesWithSubjects(
                subjects = [
                    null
                    ],
        )
        """

    def testV1PolicyRulesWithSubjects(self):
        """Test V1PolicyRulesWithSubjects"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
