# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1beta1_basic_device import V1beta1BasicDevice

class TestV1beta1BasicDevice(unittest.TestCase):
    """V1beta1BasicDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1BasicDevice:
        """Test V1beta1BasicDevice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1BasicDevice`
        """
        model = V1beta1BasicDevice()
        if include_optional:
            return V1beta1BasicDevice(
                all_nodes = True,
                allow_multiple_allocations = True,
                attributes = {
                    'key' : null
                    },
                binding_conditions = [
                    ''
                    ],
                binding_failure_conditions = [
                    ''
                    ],
                binds_to_node = True,
                capacity = {
                    'key' : null
                    },
                consumes_counters = [
                    null
                    ],
                node_name = '',
                node_selector = kubernetes_asyncio_pydantic.models.v1/node_selector.v1.NodeSelector(
                    node_selector_terms = [
                        null
                        ], ),
                taints = [
                    null
                    ]
            )
        else:
            return V1beta1BasicDevice(
        )
        """

    def testV1beta1BasicDevice(self):
        """Test V1beta1BasicDevice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
