# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_ingress_load_balancer_status import V1IngressLoadBalancerStatus

class TestV1IngressLoadBalancerStatus(unittest.TestCase):
    """V1IngressLoadBalancerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1IngressLoadBalancerStatus:
        """Test V1IngressLoadBalancerStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1IngressLoadBalancerStatus`
        """
        model = V1IngressLoadBalancerStatus()
        if include_optional:
            return V1IngressLoadBalancerStatus(
                ingress = [
                    null
                    ]
            )
        else:
            return V1IngressLoadBalancerStatus(
        )
        """

    def testV1IngressLoadBalancerStatus(self):
        """Test V1IngressLoadBalancerStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
