# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_replica_set_status import V1ReplicaSetStatus

class TestV1ReplicaSetStatus(unittest.TestCase):
    """V1ReplicaSetStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ReplicaSetStatus:
        """Test V1ReplicaSetStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ReplicaSetStatus`
        """
        model = V1ReplicaSetStatus()
        if include_optional:
            return V1ReplicaSetStatus(
                available_replicas = 56,
                conditions = [
                    null
                    ],
                fully_labeled_replicas = 56,
                observed_generation = 56,
                ready_replicas = 56,
                replicas = 56,
                terminating_replicas = 56
            )
        else:
            return V1ReplicaSetStatus(
                replicas = 56,
        )
        """

    def testV1ReplicaSetStatus(self):
        """Test V1ReplicaSetStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
