# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_replication_controller_status import V1ReplicationControllerStatus

class TestV1ReplicationControllerStatus(unittest.TestCase):
    """V1ReplicationControllerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ReplicationControllerStatus:
        """Test V1ReplicationControllerStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ReplicationControllerStatus`
        """
        model = V1ReplicationControllerStatus()
        if include_optional:
            return V1ReplicationControllerStatus(
                available_replicas = 56,
                conditions = [
                    null
                    ],
                fully_labeled_replicas = 56,
                observed_generation = 56,
                ready_replicas = 56,
                replicas = 56
            )
        else:
            return V1ReplicationControllerStatus(
                replicas = 56,
        )
        """

    def testV1ReplicationControllerStatus(self):
        """Test V1ReplicationControllerStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
