# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1alpha1_pod_certificate_request import V1alpha1PodCertificateRequest

class TestV1alpha1PodCertificateRequest(unittest.TestCase):
    """V1alpha1PodCertificateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1PodCertificateRequest:
        """Test V1alpha1PodCertificateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1PodCertificateRequest`
        """
        model = V1alpha1PodCertificateRequest()
        if include_optional:
            return V1alpha1PodCertificateRequest(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v1alpha1/pod_certificate_request_spec.v1alpha1.PodCertificateRequestSpec(
                    max_expiration_seconds = 56, 
                    node_name = '', 
                    node_uid = '', 
                    pkix_public_key = 'YQ==', 
                    pod_name = '', 
                    pod_uid = '', 
                    proof_of_possession = 'YQ==', 
                    service_account_name = '', 
                    service_account_uid = '', 
                    signer_name = '', ),
                status = kubernetes_asyncio.models.v1alpha1/pod_certificate_request_status.v1alpha1.PodCertificateRequestStatus(
                    begin_refresh_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    certificate_chain = '', 
                    conditions = [
                        null
                        ], 
                    not_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    not_before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return V1alpha1PodCertificateRequest(
                spec = kubernetes_asyncio.models.v1alpha1/pod_certificate_request_spec.v1alpha1.PodCertificateRequestSpec(
                    max_expiration_seconds = 56, 
                    node_name = '', 
                    node_uid = '', 
                    pkix_public_key = 'YQ==', 
                    pod_name = '', 
                    pod_uid = '', 
                    proof_of_possession = 'YQ==', 
                    service_account_name = '', 
                    service_account_uid = '', 
                    signer_name = '', ),
        )
        """

    def testV1alpha1PodCertificateRequest(self):
        """Test V1alpha1PodCertificateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
