# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_node_address import V1NodeAddress

class TestV1NodeAddress(unittest.TestCase):
    """V1NodeAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1NodeAddress:
        """Test V1NodeAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1NodeAddress`
        """
        model = V1NodeAddress()
        if include_optional:
            return V1NodeAddress(
                address = '',
                type = ''
            )
        else:
            return V1NodeAddress(
                address = '',
                type = '',
        )
        """

    def testV1NodeAddress(self):
        """Test V1NodeAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
