# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_namespace_status import V1NamespaceStatus

class TestV1NamespaceStatus(unittest.TestCase):
    """V1NamespaceStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1NamespaceStatus:
        """Test V1NamespaceStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1NamespaceStatus`
        """
        model = V1NamespaceStatus()
        if include_optional:
            return V1NamespaceStatus(
                conditions = [
                    null
                    ],
                phase = ''
            )
        else:
            return V1NamespaceStatus(
        )
        """

    def testV1NamespaceStatus(self):
        """Test V1NamespaceStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
