# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.api.networking_v1_api import NetworkingV1Api


class TestNetworkingV1Api(unittest.IsolatedAsyncioTestCase):
    """NetworkingV1Api unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = NetworkingV1Api()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_ingress_class(self) -> None:
        """Test case for create_ingress_class

        """
        pass

    async def test_create_ip_address(self) -> None:
        """Test case for create_ip_address

        """
        pass

    async def test_create_namespaced_ingress(self) -> None:
        """Test case for create_namespaced_ingress

        """
        pass

    async def test_create_namespaced_network_policy(self) -> None:
        """Test case for create_namespaced_network_policy

        """
        pass

    async def test_create_service_cidr(self) -> None:
        """Test case for create_service_cidr

        """
        pass

    async def test_delete_collection_ingress_class(self) -> None:
        """Test case for delete_collection_ingress_class

        """
        pass

    async def test_delete_collection_ip_address(self) -> None:
        """Test case for delete_collection_ip_address

        """
        pass

    async def test_delete_collection_namespaced_ingress(self) -> None:
        """Test case for delete_collection_namespaced_ingress

        """
        pass

    async def test_delete_collection_namespaced_network_policy(self) -> None:
        """Test case for delete_collection_namespaced_network_policy

        """
        pass

    async def test_delete_collection_service_cidr(self) -> None:
        """Test case for delete_collection_service_cidr

        """
        pass

    async def test_delete_ingress_class(self) -> None:
        """Test case for delete_ingress_class

        """
        pass

    async def test_delete_ip_address(self) -> None:
        """Test case for delete_ip_address

        """
        pass

    async def test_delete_namespaced_ingress(self) -> None:
        """Test case for delete_namespaced_ingress

        """
        pass

    async def test_delete_namespaced_network_policy(self) -> None:
        """Test case for delete_namespaced_network_policy

        """
        pass

    async def test_delete_service_cidr(self) -> None:
        """Test case for delete_service_cidr

        """
        pass

    async def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    async def test_list_ingress_class(self) -> None:
        """Test case for list_ingress_class

        """
        pass

    async def test_list_ingress_for_all_namespaces(self) -> None:
        """Test case for list_ingress_for_all_namespaces

        """
        pass

    async def test_list_ip_address(self) -> None:
        """Test case for list_ip_address

        """
        pass

    async def test_list_namespaced_ingress(self) -> None:
        """Test case for list_namespaced_ingress

        """
        pass

    async def test_list_namespaced_network_policy(self) -> None:
        """Test case for list_namespaced_network_policy

        """
        pass

    async def test_list_network_policy_for_all_namespaces(self) -> None:
        """Test case for list_network_policy_for_all_namespaces

        """
        pass

    async def test_list_service_cidr(self) -> None:
        """Test case for list_service_cidr

        """
        pass

    async def test_patch_ingress_class(self) -> None:
        """Test case for patch_ingress_class

        """
        pass

    async def test_patch_ip_address(self) -> None:
        """Test case for patch_ip_address

        """
        pass

    async def test_patch_namespaced_ingress(self) -> None:
        """Test case for patch_namespaced_ingress

        """
        pass

    async def test_patch_namespaced_ingress_status(self) -> None:
        """Test case for patch_namespaced_ingress_status

        """
        pass

    async def test_patch_namespaced_network_policy(self) -> None:
        """Test case for patch_namespaced_network_policy

        """
        pass

    async def test_patch_service_cidr(self) -> None:
        """Test case for patch_service_cidr

        """
        pass

    async def test_patch_service_cidr_status(self) -> None:
        """Test case for patch_service_cidr_status

        """
        pass

    async def test_read_ingress_class(self) -> None:
        """Test case for read_ingress_class

        """
        pass

    async def test_read_ip_address(self) -> None:
        """Test case for read_ip_address

        """
        pass

    async def test_read_namespaced_ingress(self) -> None:
        """Test case for read_namespaced_ingress

        """
        pass

    async def test_read_namespaced_ingress_status(self) -> None:
        """Test case for read_namespaced_ingress_status

        """
        pass

    async def test_read_namespaced_network_policy(self) -> None:
        """Test case for read_namespaced_network_policy

        """
        pass

    async def test_read_service_cidr(self) -> None:
        """Test case for read_service_cidr

        """
        pass

    async def test_read_service_cidr_status(self) -> None:
        """Test case for read_service_cidr_status

        """
        pass

    async def test_replace_ingress_class(self) -> None:
        """Test case for replace_ingress_class

        """
        pass

    async def test_replace_ip_address(self) -> None:
        """Test case for replace_ip_address

        """
        pass

    async def test_replace_namespaced_ingress(self) -> None:
        """Test case for replace_namespaced_ingress

        """
        pass

    async def test_replace_namespaced_ingress_status(self) -> None:
        """Test case for replace_namespaced_ingress_status

        """
        pass

    async def test_replace_namespaced_network_policy(self) -> None:
        """Test case for replace_namespaced_network_policy

        """
        pass

    async def test_replace_service_cidr(self) -> None:
        """Test case for replace_service_cidr

        """
        pass

    async def test_replace_service_cidr_status(self) -> None:
        """Test case for replace_service_cidr_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
