# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1beta1_device_claim import V1beta1DeviceClaim

class TestV1beta1DeviceClaim(unittest.TestCase):
    """V1beta1DeviceClaim unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1DeviceClaim:
        """Test V1beta1DeviceClaim
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1DeviceClaim`
        """
        model = V1beta1DeviceClaim()
        if include_optional:
            return V1beta1DeviceClaim(
                config = [
                    null
                    ],
                constraints = [
                    null
                    ],
                requests = [
                    null
                    ]
            )
        else:
            return V1beta1DeviceClaim(
        )
        """

    def testV1beta1DeviceClaim(self):
        """Test V1beta1DeviceClaim"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
