# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.api.version_api import VersionApi


class TestVersionApi(unittest.IsolatedAsyncioTestCase):
    """VersionApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = VersionApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_code(self) -> None:
        """Test case for get_code

        """
        pass


if __name__ == '__main__':
    unittest.main()
