# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_topology_selector_term import V1TopologySelectorTerm

class TestV1TopologySelectorTerm(unittest.TestCase):
    """V1TopologySelectorTerm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1TopologySelectorTerm:
        """Test V1TopologySelectorTerm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1TopologySelectorTerm`
        """
        model = V1TopologySelectorTerm()
        if include_optional:
            return V1TopologySelectorTerm(
                match_label_expressions = [
                    null
                    ]
            )
        else:
            return V1TopologySelectorTerm(
        )
        """

    def testV1TopologySelectorTerm(self):
        """Test V1TopologySelectorTerm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
