# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_ingress_status import V1IngressStatus

class TestV1IngressStatus(unittest.TestCase):
    """V1IngressStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1IngressStatus:
        """Test V1IngressStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1IngressStatus`
        """
        model = V1IngressStatus()
        if include_optional:
            return V1IngressStatus(
                load_balancer = kubernetes_asyncio.models.v1/ingress_load_balancer_status.v1.IngressLoadBalancerStatus(
                    ingress = [
                        null
                        ], )
            )
        else:
            return V1IngressStatus(
        )
        """

    def testV1IngressStatus(self):
        """Test V1IngressStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
