# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1beta1_service_cidr_status import V1beta1ServiceCIDRStatus

class TestV1beta1ServiceCIDRStatus(unittest.TestCase):
    """V1beta1ServiceCIDRStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1ServiceCIDRStatus:
        """Test V1beta1ServiceCIDRStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1ServiceCIDRStatus`
        """
        model = V1beta1ServiceCIDRStatus()
        if include_optional:
            return V1beta1ServiceCIDRStatus(
                conditions = [
                    null
                    ]
            )
        else:
            return V1beta1ServiceCIDRStatus(
        )
        """

    def testV1beta1ServiceCIDRStatus(self):
        """Test V1beta1ServiceCIDRStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
