# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v2_horizontal_pod_autoscaler import V2HorizontalPodAutoscaler

class TestV2HorizontalPodAutoscaler(unittest.TestCase):
    """V2HorizontalPodAutoscaler unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V2HorizontalPodAutoscaler:
        """Test V2HorizontalPodAutoscaler
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V2HorizontalPodAutoscaler`
        """
        model = V2HorizontalPodAutoscaler()
        if include_optional:
            return V2HorizontalPodAutoscaler(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v2/horizontal_pod_autoscaler_spec.v2.HorizontalPodAutoscalerSpec(
                    behavior = null, 
                    max_replicas = 56, 
                    metrics = [
                        null
                        ], 
                    min_replicas = 56, 
                    scale_target_ref = null, ),
                status = kubernetes_asyncio.models.v2/horizontal_pod_autoscaler_status.v2.HorizontalPodAutoscalerStatus(
                    conditions = [
                        null
                        ], 
                    current_metrics = [
                        null
                        ], 
                    current_replicas = 56, 
                    desired_replicas = 56, 
                    last_scale_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    observed_generation = 56, )
            )
        else:
            return V2HorizontalPodAutoscaler(
        )
        """

    def testV2HorizontalPodAutoscaler(self):
        """Test V2HorizontalPodAutoscaler"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
