# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.models.v1alpha1_mutating_admission_policy import V1alpha1MutatingAdmissionPolicy

class TestV1alpha1MutatingAdmissionPolicy(unittest.TestCase):
    """V1alpha1MutatingAdmissionPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1MutatingAdmissionPolicy:
        """Test V1alpha1MutatingAdmissionPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1MutatingAdmissionPolicy`
        """
        model = V1alpha1MutatingAdmissionPolicy()
        if include_optional:
            return V1alpha1MutatingAdmissionPolicy(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.client.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        kubernetes_asyncio.client.models.v1/managed_fields_entry.v1.ManagedFieldsEntry(
                            api_version = '', 
                            fields_type = '', 
                            fields_v1 = kubernetes_asyncio.client.models.fields_v1.fieldsV1(), 
                            manager = '', 
                            operation = '', 
                            subresource = '', 
                            time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        kubernetes_asyncio.client.models.v1/owner_reference.v1.OwnerReference(
                            api_version = '', 
                            block_owner_deletion = True, 
                            controller = True, 
                            kind = '', 
                            name = '', 
                            uid = '', )
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.client.models.v1alpha1/mutating_admission_policy_spec.v1alpha1.MutatingAdmissionPolicySpec(
                    failure_policy = '', 
                    match_conditions = [
                        kubernetes_asyncio.client.models.v1alpha1/match_condition.v1alpha1.MatchCondition(
                            expression = '', 
                            name = '', )
                        ], 
                    match_constraints = kubernetes_asyncio.client.models.v1alpha1/match_resources.v1alpha1.MatchResources(
                        exclude_resource_rules = [
                            kubernetes_asyncio.client.models.v1alpha1/named_rule_with_operations.v1alpha1.NamedRuleWithOperations(
                                api_groups = [
                                    ''
                                    ], 
                                api_versions = [
                                    ''
                                    ], 
                                operations = [
                                    ''
                                    ], 
                                resource_names = [
                                    ''
                                    ], 
                                resources = [
                                    ''
                                    ], 
                                scope = '', )
                            ], 
                        match_policy = '', 
                        namespace_selector = kubernetes_asyncio.client.models.v1/label_selector.v1.LabelSelector(
                            match_expressions = [
                                kubernetes_asyncio.client.models.v1/label_selector_requirement.v1.LabelSelectorRequirement(
                                    key = '', 
                                    operator = '', 
                                    values = [
                                        ''
                                        ], )
                                ], 
                            match_labels = {
                                'key' : ''
                                }, ), 
                        object_selector = kubernetes_asyncio.client.models.v1/label_selector.v1.LabelSelector(), 
                        resource_rules = [
                            kubernetes_asyncio.client.models.v1alpha1/named_rule_with_operations.v1alpha1.NamedRuleWithOperations(
                                scope = '', )
                            ], ), 
                    mutations = [
                        kubernetes_asyncio.client.models.v1alpha1/mutation.v1alpha1.Mutation(
                            apply_configuration = kubernetes_asyncio.client.models.v1alpha1/apply_configuration.v1alpha1.ApplyConfiguration(
                                expression = '', ), 
                            json_patch = kubernetes_asyncio.client.models.v1alpha1/json_patch.v1alpha1.JSONPatch(
                                expression = '', ), 
                            patch_type = '', )
                        ], 
                    param_kind = kubernetes_asyncio.client.models.v1alpha1/param_kind.v1alpha1.ParamKind(
                        api_version = '', 
                        kind = '', ), 
                    reinvocation_policy = '', 
                    variables = [
                        kubernetes_asyncio.client.models.v1alpha1/variable.v1alpha1.Variable(
                            expression = '', 
                            name = '', )
                        ], )
            )
        else:
            return V1alpha1MutatingAdmissionPolicy(
        )
        """

    def testV1alpha1MutatingAdmissionPolicy(self):
        """Test V1alpha1MutatingAdmissionPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
