# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_device_allocation_configuration import V1DeviceAllocationConfiguration

class TestV1DeviceAllocationConfiguration(unittest.TestCase):
    """V1DeviceAllocationConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DeviceAllocationConfiguration:
        """Test V1DeviceAllocationConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DeviceAllocationConfiguration`
        """
        model = V1DeviceAllocationConfiguration()
        if include_optional:
            return V1DeviceAllocationConfiguration(
                opaque = kubernetes_asyncio_pydantic.models.v1/opaque_device_configuration.v1.OpaqueDeviceConfiguration(
                    driver = '', 
                    parameters = null, ),
                requests = [
                    ''
                    ],
                source = ''
            )
        else:
            return V1DeviceAllocationConfiguration(
                source = '',
        )
        """

    def testV1DeviceAllocationConfiguration(self):
        """Test V1DeviceAllocationConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
