# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_volume_attachment_spec import V1VolumeAttachmentSpec

class TestV1VolumeAttachmentSpec(unittest.TestCase):
    """V1VolumeAttachmentSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1VolumeAttachmentSpec:
        """Test V1VolumeAttachmentSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1VolumeAttachmentSpec`
        """
        model = V1VolumeAttachmentSpec()
        if include_optional:
            return V1VolumeAttachmentSpec(
                attacher = '',
                node_name = '',
                source = kubernetes_asyncio_pydantic.models.v1/volume_attachment_source.v1.VolumeAttachmentSource(
                    inline_volume_spec = null, 
                    persistent_volume_name = '', )
            )
        else:
            return V1VolumeAttachmentSpec(
                attacher = '',
                node_name = '',
                source = kubernetes_asyncio_pydantic.models.v1/volume_attachment_source.v1.VolumeAttachmentSource(
                    inline_volume_spec = null, 
                    persistent_volume_name = '', ),
        )
        """

    def testV1VolumeAttachmentSpec(self):
        """Test V1VolumeAttachmentSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
