# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_horizontal_pod_autoscaler import V1HorizontalPodAutoscaler

class TestV1HorizontalPodAutoscaler(unittest.TestCase):
    """V1HorizontalPodAutoscaler unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1HorizontalPodAutoscaler:
        """Test V1HorizontalPodAutoscaler
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1HorizontalPodAutoscaler`
        """
        model = V1HorizontalPodAutoscaler()
        if include_optional:
            return V1HorizontalPodAutoscaler(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio_pydantic.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio_pydantic.models.v1/horizontal_pod_autoscaler_spec.v1.HorizontalPodAutoscalerSpec(
                    max_replicas = 56, 
                    min_replicas = 56, 
                    scale_target_ref = null, 
                    target_cpu_utilization_percentage = 56, ),
                status = kubernetes_asyncio_pydantic.models.v1/horizontal_pod_autoscaler_status.v1.HorizontalPodAutoscalerStatus(
                    current_cpu_utilization_percentage = 56, 
                    current_replicas = 56, 
                    desired_replicas = 56, 
                    last_scale_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    observed_generation = 56, )
            )
        else:
            return V1HorizontalPodAutoscaler(
        )
        """

    def testV1HorizontalPodAutoscaler(self):
        """Test V1HorizontalPodAutoscaler"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
