# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_service_reference1 import V1ServiceReference1

class TestV1ServiceReference1(unittest.TestCase):
    """V1ServiceReference1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ServiceReference1:
        """Test V1ServiceReference1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ServiceReference1`
        """
        model = V1ServiceReference1()
        if include_optional:
            return V1ServiceReference1(
                name = '',
                namespace = '',
                path = '',
                port = 56
            )
        else:
            return V1ServiceReference1(
                name = '',
                namespace = '',
        )
        """

    def testV1ServiceReference1(self):
        """Test V1ServiceReference1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
