# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_flow_schema import V1FlowSchema

class TestV1FlowSchema(unittest.TestCase):
    """V1FlowSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FlowSchema:
        """Test V1FlowSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FlowSchema`
        """
        model = V1FlowSchema()
        if include_optional:
            return V1FlowSchema(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio_pydantic.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio_pydantic.models.v1/flow_schema_spec.v1.FlowSchemaSpec(
                    distinguisher_method = null, 
                    matching_precedence = 56, 
                    priority_level_configuration = null, 
                    rules = [
                        null
                        ], ),
                status = kubernetes_asyncio_pydantic.models.v1/flow_schema_status.v1.FlowSchemaStatus(
                    conditions = [
                        null
                        ], )
            )
        else:
            return V1FlowSchema(
        )
        """

    def testV1FlowSchema(self):
        """Test V1FlowSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
