# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.models.v1_service_cidr_spec import V1ServiceCIDRSpec

class TestV1ServiceCIDRSpec(unittest.TestCase):
    """V1ServiceCIDRSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ServiceCIDRSpec:
        """Test V1ServiceCIDRSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ServiceCIDRSpec`
        """
        model = V1ServiceCIDRSpec()
        if include_optional:
            return V1ServiceCIDRSpec(
                cidrs = [
                    ''
                    ]
            )
        else:
            return V1ServiceCIDRSpec(
        )
        """

    def testV1ServiceCIDRSpec(self):
        """Test V1ServiceCIDRSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
