# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.api.discovery_v1_api import DiscoveryV1Api


class TestDiscoveryV1Api(unittest.IsolatedAsyncioTestCase):
    """DiscoveryV1Api unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DiscoveryV1Api()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_namespaced_endpoint_slice(self) -> None:
        """Test case for create_namespaced_endpoint_slice

        """
        pass

    async def test_delete_collection_namespaced_endpoint_slice(self) -> None:
        """Test case for delete_collection_namespaced_endpoint_slice

        """
        pass

    async def test_delete_namespaced_endpoint_slice(self) -> None:
        """Test case for delete_namespaced_endpoint_slice

        """
        pass

    async def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    async def test_list_endpoint_slice_for_all_namespaces(self) -> None:
        """Test case for list_endpoint_slice_for_all_namespaces

        """
        pass

    async def test_list_namespaced_endpoint_slice(self) -> None:
        """Test case for list_namespaced_endpoint_slice

        """
        pass

    async def test_patch_namespaced_endpoint_slice(self) -> None:
        """Test case for patch_namespaced_endpoint_slice

        """
        pass

    async def test_read_namespaced_endpoint_slice(self) -> None:
        """Test case for read_namespaced_endpoint_slice

        """
        pass

    async def test_replace_namespaced_endpoint_slice(self) -> None:
        """Test case for replace_namespaced_endpoint_slice

        """
        pass


if __name__ == '__main__':
    unittest.main()
