# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_service_status import V1ServiceStatus

class TestV1ServiceStatus(unittest.TestCase):
    """V1ServiceStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ServiceStatus:
        """Test V1ServiceStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ServiceStatus`
        """
        model = V1ServiceStatus()
        if include_optional:
            return V1ServiceStatus(
                conditions = [
                    null
                    ],
                load_balancer = kubernetes_asyncio.models.v1/load_balancer_status.v1.LoadBalancerStatus(
                    ingress = [
                        null
                        ], )
            )
        else:
            return V1ServiceStatus(
        )
        """

    def testV1ServiceStatus(self):
        """Test V1ServiceStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
