# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_device_selector import V1DeviceSelector

class TestV1DeviceSelector(unittest.TestCase):
    """V1DeviceSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DeviceSelector:
        """Test V1DeviceSelector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DeviceSelector`
        """
        model = V1DeviceSelector()
        if include_optional:
            return V1DeviceSelector(
                cel = kubernetes_asyncio_pydantic.models.v1/cel_device_selector.v1.CELDeviceSelector(
                    expression = '', )
            )
        else:
            return V1DeviceSelector(
        )
        """

    def testV1DeviceSelector(self):
        """Test V1DeviceSelector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
