# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1beta2_device_counter_consumption import V1beta2DeviceCounterConsumption

class TestV1beta2DeviceCounterConsumption(unittest.TestCase):
    """V1beta2DeviceCounterConsumption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta2DeviceCounterConsumption:
        """Test V1beta2DeviceCounterConsumption
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta2DeviceCounterConsumption`
        """
        model = V1beta2DeviceCounterConsumption()
        if include_optional:
            return V1beta2DeviceCounterConsumption(
                counter_set = '',
                counters = {
                    'key' : null
                    }
            )
        else:
            return V1beta2DeviceCounterConsumption(
                counter_set = '',
                counters = {
                    'key' : null
                    },
        )
        """

    def testV1beta2DeviceCounterConsumption(self):
        """Test V1beta2DeviceCounterConsumption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
