# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1alpha1_validating_admission_policy_binding_spec import V1alpha1ValidatingAdmissionPolicyBindingSpec

class TestV1alpha1ValidatingAdmissionPolicyBindingSpec(unittest.TestCase):
    """V1alpha1ValidatingAdmissionPolicyBindingSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1ValidatingAdmissionPolicyBindingSpec:
        """Test V1alpha1ValidatingAdmissionPolicyBindingSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1ValidatingAdmissionPolicyBindingSpec`
        """
        model = V1alpha1ValidatingAdmissionPolicyBindingSpec()
        if include_optional:
            return V1alpha1ValidatingAdmissionPolicyBindingSpec(
                match_resources = kubernetes_asyncio.models.v1alpha1/match_resources.v1alpha1.MatchResources(
                    exclude_resource_rules = [
                        null
                        ], 
                    match_policy = '', 
                    namespace_selector = null, 
                    object_selector = null, 
                    resource_rules = [
                        null
                        ], ),
                param_ref = kubernetes_asyncio.models.v1alpha1/param_ref.v1alpha1.ParamRef(
                    name = '', 
                    namespace = '', 
                    parameter_not_found_action = '', 
                    selector = null, ),
                policy_name = '',
                validation_actions = [
                    ''
                    ]
            )
        else:
            return V1alpha1ValidatingAdmissionPolicyBindingSpec(
        )
        """

    def testV1alpha1ValidatingAdmissionPolicyBindingSpec(self):
        """Test V1alpha1ValidatingAdmissionPolicyBindingSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
