# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1alpha1_storage_version_status import V1alpha1StorageVersionStatus

class TestV1alpha1StorageVersionStatus(unittest.TestCase):
    """V1alpha1StorageVersionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1StorageVersionStatus:
        """Test V1alpha1StorageVersionStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1StorageVersionStatus`
        """
        model = V1alpha1StorageVersionStatus()
        if include_optional:
            return V1alpha1StorageVersionStatus(
                common_encoding_version = '',
                conditions = [
                    null
                    ],
                storage_versions = [
                    null
                    ]
            )
        else:
            return V1alpha1StorageVersionStatus(
        )
        """

    def testV1alpha1StorageVersionStatus(self):
        """Test V1alpha1StorageVersionStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
