# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1beta1_capacity_request_policy import V1beta1CapacityRequestPolicy

class TestV1beta1CapacityRequestPolicy(unittest.TestCase):
    """V1beta1CapacityRequestPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1CapacityRequestPolicy:
        """Test V1beta1CapacityRequestPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1CapacityRequestPolicy`
        """
        model = V1beta1CapacityRequestPolicy()
        if include_optional:
            return V1beta1CapacityRequestPolicy(
                default = None,
                valid_range = kubernetes_asyncio.models.v1beta1/capacity_request_policy_range.v1beta1.CapacityRequestPolicyRange(
                    max = null, 
                    min = null, 
                    step = null, ),
                valid_values = [
                    kubernetes_asyncio.models.v1_pod_spec_overhead_value.v1_PodSpec_overhead_value()
                    ]
            )
        else:
            return V1beta1CapacityRequestPolicy(
        )
        """

    def testV1beta1CapacityRequestPolicy(self):
        """Test V1beta1CapacityRequestPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
