# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_stateful_set import V1StatefulSet

class TestV1StatefulSet(unittest.TestCase):
    """V1StatefulSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1StatefulSet:
        """Test V1StatefulSet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1StatefulSet`
        """
        model = V1StatefulSet()
        if include_optional:
            return V1StatefulSet(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v1/stateful_set_spec.v1.StatefulSetSpec(
                    min_ready_seconds = 56, 
                    ordinals = null, 
                    persistent_volume_claim_retention_policy = null, 
                    pod_management_policy = '', 
                    replicas = 56, 
                    revision_history_limit = 56, 
                    selector = null, 
                    service_name = '', 
                    template = null, 
                    update_strategy = null, 
                    volume_claim_templates = [
                        null
                        ], ),
                status = kubernetes_asyncio.models.v1/stateful_set_status.v1.StatefulSetStatus(
                    available_replicas = 56, 
                    collision_count = 56, 
                    conditions = [
                        null
                        ], 
                    current_replicas = 56, 
                    current_revision = '', 
                    observed_generation = 56, 
                    ready_replicas = 56, 
                    replicas = 56, 
                    update_revision = '', 
                    updated_replicas = 56, )
            )
        else:
            return V1StatefulSet(
        )
        """

    def testV1StatefulSet(self):
        """Test V1StatefulSet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
