# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.models.v1beta2_device_class_configuration import V1beta2DeviceClassConfiguration

class TestV1beta2DeviceClassConfiguration(unittest.TestCase):
    """V1beta2DeviceClassConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta2DeviceClassConfiguration:
        """Test V1beta2DeviceClassConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta2DeviceClassConfiguration`
        """
        model = V1beta2DeviceClassConfiguration()
        if include_optional:
            return V1beta2DeviceClassConfiguration(
                opaque = kubernetes_asyncio.client.models.v1beta2/opaque_device_configuration.v1beta2.OpaqueDeviceConfiguration(
                    driver = '', 
                    parameters = kubernetes_asyncio.client.models.parameters.parameters(), )
            )
        else:
            return V1beta2DeviceClassConfiguration(
        )
        """

    def testV1beta2DeviceClassConfiguration(self):
        """Test V1beta2DeviceClassConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
