# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1beta1_mutating_admission_policy_binding import V1beta1MutatingAdmissionPolicyBinding

class TestV1beta1MutatingAdmissionPolicyBinding(unittest.TestCase):
    """V1beta1MutatingAdmissionPolicyBinding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1MutatingAdmissionPolicyBinding:
        """Test V1beta1MutatingAdmissionPolicyBinding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1MutatingAdmissionPolicyBinding`
        """
        model = V1beta1MutatingAdmissionPolicyBinding()
        if include_optional:
            return V1beta1MutatingAdmissionPolicyBinding(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio_pydantic.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio_pydantic.models.v1beta1/mutating_admission_policy_binding_spec.v1beta1.MutatingAdmissionPolicyBindingSpec(
                    match_resources = null, 
                    param_ref = null, 
                    policy_name = '', )
            )
        else:
            return V1beta1MutatingAdmissionPolicyBinding(
        )
        """

    def testV1beta1MutatingAdmissionPolicyBinding(self):
        """Test V1beta1MutatingAdmissionPolicyBinding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
