# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.models.v1beta1_cel_device_selector import V1beta1CELDeviceSelector

class TestV1beta1CELDeviceSelector(unittest.TestCase):
    """V1beta1CELDeviceSelector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1CELDeviceSelector:
        """Test V1beta1CELDeviceSelector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1CELDeviceSelector`
        """
        model = V1beta1CELDeviceSelector()
        if include_optional:
            return V1beta1CELDeviceSelector(
                expression = ''
            )
        else:
            return V1beta1CELDeviceSelector(
                expression = '',
        )
        """

    def testV1beta1CELDeviceSelector(self):
        """Test V1beta1CELDeviceSelector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
