# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1beta3_priority_level_configuration_spec import V1beta3PriorityLevelConfigurationSpec

class TestV1beta3PriorityLevelConfigurationSpec(unittest.TestCase):
    """V1beta3PriorityLevelConfigurationSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta3PriorityLevelConfigurationSpec:
        """Test V1beta3PriorityLevelConfigurationSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta3PriorityLevelConfigurationSpec`
        """
        model = V1beta3PriorityLevelConfigurationSpec()
        if include_optional:
            return V1beta3PriorityLevelConfigurationSpec(
                exempt = kubernetes_asyncio.models.v1beta3/exempt_priority_level_configuration.v1beta3.ExemptPriorityLevelConfiguration(
                    lendable_percent = 56, 
                    nominal_concurrency_shares = 56, ),
                limited = kubernetes_asyncio.models.v1beta3/limited_priority_level_configuration.v1beta3.LimitedPriorityLevelConfiguration(
                    borrowing_limit_percent = 56, 
                    lendable_percent = 56, 
                    limit_response = null, 
                    nominal_concurrency_shares = 56, ),
                type = ''
            )
        else:
            return V1beta3PriorityLevelConfigurationSpec(
                type = '',
        )
        """

    def testV1beta3PriorityLevelConfigurationSpec(self):
        """Test V1beta3PriorityLevelConfigurationSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
