# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1beta2_device_class import V1beta2DeviceClass

class TestV1beta2DeviceClass(unittest.TestCase):
    """V1beta2DeviceClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta2DeviceClass:
        """Test V1beta2DeviceClass
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta2DeviceClass`
        """
        model = V1beta2DeviceClass()
        if include_optional:
            return V1beta2DeviceClass(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v1beta2/device_class_spec.v1beta2.DeviceClassSpec(
                    config = [
                        null
                        ], 
                    extended_resource_name = '', 
                    selectors = [
                        null
                        ], )
            )
        else:
            return V1beta2DeviceClass(
                spec = kubernetes_asyncio.models.v1beta2/device_class_spec.v1beta2.DeviceClassSpec(
                    config = [
                        null
                        ], 
                    extended_resource_name = '', 
                    selectors = [
                        null
                        ], ),
        )
        """

    def testV1beta2DeviceClass(self):
        """Test V1beta2DeviceClass"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
