# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.api.networking_api import NetworkingApi


class TestNetworkingApi(unittest.IsolatedAsyncioTestCase):
    """NetworkingApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = NetworkingApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_api_group(self) -> None:
        """Test case for get_api_group

        """
        pass


if __name__ == '__main__':
    unittest.main()
