# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1alpha2_resource_class import V1alpha2ResourceClass

class TestV1alpha2ResourceClass(unittest.TestCase):
    """V1alpha2ResourceClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha2ResourceClass:
        """Test V1alpha2ResourceClass
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha2ResourceClass`
        """
        model = V1alpha2ResourceClass()
        if include_optional:
            return V1alpha2ResourceClass(
                api_version = '',
                driver_name = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                parameters_ref = kubernetes_asyncio.models.v1alpha2/resource_class_parameters_reference.v1alpha2.ResourceClassParametersReference(
                    api_group = '', 
                    kind = '', 
                    name = '', 
                    namespace = '', ),
                structured_parameters = True,
                suitable_nodes = kubernetes_asyncio.models.v1/node_selector.v1.NodeSelector(
                    node_selector_terms = [
                        null
                        ], )
            )
        else:
            return V1alpha2ResourceClass(
                driver_name = '',
        )
        """

    def testV1alpha2ResourceClass(self):
        """Test V1alpha2ResourceClass"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
