# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.api.custom_objects_api import CustomObjectsApi


class TestCustomObjectsApi(unittest.IsolatedAsyncioTestCase):
    """CustomObjectsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CustomObjectsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_cluster_custom_object(self) -> None:
        """Test case for create_cluster_custom_object

        """
        pass

    async def test_create_namespaced_custom_object(self) -> None:
        """Test case for create_namespaced_custom_object

        """
        pass

    async def test_delete_cluster_custom_object(self) -> None:
        """Test case for delete_cluster_custom_object

        """
        pass

    async def test_delete_collection_cluster_custom_object(self) -> None:
        """Test case for delete_collection_cluster_custom_object

        """
        pass

    async def test_delete_collection_namespaced_custom_object(self) -> None:
        """Test case for delete_collection_namespaced_custom_object

        """
        pass

    async def test_delete_namespaced_custom_object(self) -> None:
        """Test case for delete_namespaced_custom_object

        """
        pass

    async def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    async def test_get_cluster_custom_object(self) -> None:
        """Test case for get_cluster_custom_object

        """
        pass

    async def test_get_cluster_custom_object_scale(self) -> None:
        """Test case for get_cluster_custom_object_scale

        """
        pass

    async def test_get_cluster_custom_object_status(self) -> None:
        """Test case for get_cluster_custom_object_status

        """
        pass

    async def test_get_namespaced_custom_object(self) -> None:
        """Test case for get_namespaced_custom_object

        """
        pass

    async def test_get_namespaced_custom_object_scale(self) -> None:
        """Test case for get_namespaced_custom_object_scale

        """
        pass

    async def test_get_namespaced_custom_object_status(self) -> None:
        """Test case for get_namespaced_custom_object_status

        """
        pass

    async def test_list_cluster_custom_object(self) -> None:
        """Test case for list_cluster_custom_object

        """
        pass

    async def test_list_custom_object_for_all_namespaces(self) -> None:
        """Test case for list_custom_object_for_all_namespaces

        """
        pass

    async def test_list_namespaced_custom_object(self) -> None:
        """Test case for list_namespaced_custom_object

        """
        pass

    async def test_patch_cluster_custom_object(self) -> None:
        """Test case for patch_cluster_custom_object

        """
        pass

    async def test_patch_cluster_custom_object_scale(self) -> None:
        """Test case for patch_cluster_custom_object_scale

        """
        pass

    async def test_patch_cluster_custom_object_status(self) -> None:
        """Test case for patch_cluster_custom_object_status

        """
        pass

    async def test_patch_namespaced_custom_object(self) -> None:
        """Test case for patch_namespaced_custom_object

        """
        pass

    async def test_patch_namespaced_custom_object_scale(self) -> None:
        """Test case for patch_namespaced_custom_object_scale

        """
        pass

    async def test_patch_namespaced_custom_object_status(self) -> None:
        """Test case for patch_namespaced_custom_object_status

        """
        pass

    async def test_replace_cluster_custom_object(self) -> None:
        """Test case for replace_cluster_custom_object

        """
        pass

    async def test_replace_cluster_custom_object_scale(self) -> None:
        """Test case for replace_cluster_custom_object_scale

        """
        pass

    async def test_replace_cluster_custom_object_status(self) -> None:
        """Test case for replace_cluster_custom_object_status

        """
        pass

    async def test_replace_namespaced_custom_object(self) -> None:
        """Test case for replace_namespaced_custom_object

        """
        pass

    async def test_replace_namespaced_custom_object_scale(self) -> None:
        """Test case for replace_namespaced_custom_object_scale

        """
        pass

    async def test_replace_namespaced_custom_object_status(self) -> None:
        """Test case for replace_namespaced_custom_object_status

        """
        pass


if __name__ == '__main__':
    unittest.main()
