# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_job_template_spec import V1JobTemplateSpec

class TestV1JobTemplateSpec(unittest.TestCase):
    """V1JobTemplateSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1JobTemplateSpec:
        """Test V1JobTemplateSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1JobTemplateSpec`
        """
        model = V1JobTemplateSpec()
        if include_optional:
            return V1JobTemplateSpec(
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v1/job_spec.v1.JobSpec(
                    active_deadline_seconds = 56, 
                    backoff_limit = 56, 
                    backoff_limit_per_index = 56, 
                    completion_mode = '', 
                    completions = 56, 
                    managed_by = '', 
                    manual_selector = True, 
                    max_failed_indexes = 56, 
                    parallelism = 56, 
                    pod_failure_policy = null, 
                    pod_replacement_policy = '', 
                    selector = null, 
                    success_policy = null, 
                    suspend = True, 
                    template = null, 
                    ttl_seconds_after_finished = 56, )
            )
        else:
            return V1JobTemplateSpec(
        )
        """

    def testV1JobTemplateSpec(self):
        """Test V1JobTemplateSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
