# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1alpha1_validating_admission_policy_binding import V1alpha1ValidatingAdmissionPolicyBinding

class TestV1alpha1ValidatingAdmissionPolicyBinding(unittest.TestCase):
    """V1alpha1ValidatingAdmissionPolicyBinding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1ValidatingAdmissionPolicyBinding:
        """Test V1alpha1ValidatingAdmissionPolicyBinding
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1ValidatingAdmissionPolicyBinding`
        """
        model = V1alpha1ValidatingAdmissionPolicyBinding()
        if include_optional:
            return V1alpha1ValidatingAdmissionPolicyBinding(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v1alpha1/validating_admission_policy_binding_spec.v1alpha1.ValidatingAdmissionPolicyBindingSpec(
                    match_resources = null, 
                    param_ref = null, 
                    policy_name = '', 
                    validation_actions = [
                        ''
                        ], )
            )
        else:
            return V1alpha1ValidatingAdmissionPolicyBinding(
        )
        """

    def testV1alpha1ValidatingAdmissionPolicyBinding(self):
        """Test V1alpha1ValidatingAdmissionPolicyBinding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
