# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1beta1_resource_claim_status import V1beta1ResourceClaimStatus

class TestV1beta1ResourceClaimStatus(unittest.TestCase):
    """V1beta1ResourceClaimStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1ResourceClaimStatus:
        """Test V1beta1ResourceClaimStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1ResourceClaimStatus`
        """
        model = V1beta1ResourceClaimStatus()
        if include_optional:
            return V1beta1ResourceClaimStatus(
                allocation = kubernetes_asyncio_pydantic.models.v1beta1/allocation_result.v1beta1.AllocationResult(
                    devices = null, 
                    node_selector = null, ),
                devices = [
                    null
                    ],
                reserved_for = [
                    null
                    ]
            )
        else:
            return V1beta1ResourceClaimStatus(
        )
        """

    def testV1beta1ResourceClaimStatus(self):
        """Test V1beta1ResourceClaimStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
