# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_local_subject_access_review import V1LocalSubjectAccessReview

class TestV1LocalSubjectAccessReview(unittest.TestCase):
    """V1LocalSubjectAccessReview unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1LocalSubjectAccessReview:
        """Test V1LocalSubjectAccessReview
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1LocalSubjectAccessReview`
        """
        model = V1LocalSubjectAccessReview()
        if include_optional:
            return V1LocalSubjectAccessReview(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v1/subject_access_review_spec.v1.SubjectAccessReviewSpec(
                    extra = {
                        'key' : [
                            ''
                            ]
                        }, 
                    groups = [
                        ''
                        ], 
                    non_resource_attributes = null, 
                    resource_attributes = null, 
                    uid = '', 
                    user = '', ),
                status = kubernetes_asyncio.models.v1/subject_access_review_status.v1.SubjectAccessReviewStatus(
                    allowed = True, 
                    denied = True, 
                    evaluation_error = '', 
                    reason = '', )
            )
        else:
            return V1LocalSubjectAccessReview(
                spec = kubernetes_asyncio.models.v1/subject_access_review_spec.v1.SubjectAccessReviewSpec(
                    extra = {
                        'key' : [
                            ''
                            ]
                        }, 
                    groups = [
                        ''
                        ], 
                    non_resource_attributes = null, 
                    resource_attributes = null, 
                    uid = '', 
                    user = '', ),
        )
        """

    def testV1LocalSubjectAccessReview(self):
        """Test V1LocalSubjectAccessReview"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
