# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_downward_api_volume_source import V1DownwardAPIVolumeSource

class TestV1DownwardAPIVolumeSource(unittest.TestCase):
    """V1DownwardAPIVolumeSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DownwardAPIVolumeSource:
        """Test V1DownwardAPIVolumeSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DownwardAPIVolumeSource`
        """
        model = V1DownwardAPIVolumeSource()
        if include_optional:
            return V1DownwardAPIVolumeSource(
                default_mode = 56,
                items = [
                    null
                    ]
            )
        else:
            return V1DownwardAPIVolumeSource(
        )
        """

    def testV1DownwardAPIVolumeSource(self):
        """Test V1DownwardAPIVolumeSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
