# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1beta1_capacity_request_policy_range_step import V1beta1CapacityRequestPolicyRangeStep

class TestV1beta1CapacityRequestPolicyRangeStep(unittest.TestCase):
    """V1beta1CapacityRequestPolicyRangeStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1beta1CapacityRequestPolicyRangeStep:
        """Test V1beta1CapacityRequestPolicyRangeStep
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1beta1CapacityRequestPolicyRangeStep`
        """
        model = V1beta1CapacityRequestPolicyRangeStep()
        if include_optional:
            return V1beta1CapacityRequestPolicyRangeStep(
            )
        else:
            return V1beta1CapacityRequestPolicyRangeStep(
        )
        """

    def testV1beta1CapacityRequestPolicyRangeStep(self):
        """Test V1beta1CapacityRequestPolicyRangeStep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
