# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.api.coordination_v1beta1_api import CoordinationV1beta1Api


class TestCoordinationV1beta1Api(unittest.IsolatedAsyncioTestCase):
    """CoordinationV1beta1Api unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = CoordinationV1beta1Api()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_create_namespaced_lease_candidate(self) -> None:
        """Test case for create_namespaced_lease_candidate

        """
        pass

    async def test_delete_collection_namespaced_lease_candidate(self) -> None:
        """Test case for delete_collection_namespaced_lease_candidate

        """
        pass

    async def test_delete_namespaced_lease_candidate(self) -> None:
        """Test case for delete_namespaced_lease_candidate

        """
        pass

    async def test_get_api_resources(self) -> None:
        """Test case for get_api_resources

        """
        pass

    async def test_list_lease_candidate_for_all_namespaces(self) -> None:
        """Test case for list_lease_candidate_for_all_namespaces

        """
        pass

    async def test_list_namespaced_lease_candidate(self) -> None:
        """Test case for list_namespaced_lease_candidate

        """
        pass

    async def test_patch_namespaced_lease_candidate(self) -> None:
        """Test case for patch_namespaced_lease_candidate

        """
        pass

    async def test_read_namespaced_lease_candidate(self) -> None:
        """Test case for read_namespaced_lease_candidate

        """
        pass

    async def test_replace_namespaced_lease_candidate(self) -> None:
        """Test case for replace_namespaced_lease_candidate

        """
        pass


if __name__ == '__main__':
    unittest.main()
