# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_device_capacity import V1DeviceCapacity

class TestV1DeviceCapacity(unittest.TestCase):
    """V1DeviceCapacity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DeviceCapacity:
        """Test V1DeviceCapacity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DeviceCapacity`
        """
        model = V1DeviceCapacity()
        if include_optional:
            return V1DeviceCapacity(
                request_policy = kubernetes_asyncio_pydantic.models.v1/capacity_request_policy.v1.CapacityRequestPolicy(
                    default = null, 
                    valid_range = null, 
                    valid_values = [
                        kubernetes_asyncio_pydantic.models.v1_pod_spec_overhead_value.v1_PodSpec_overhead_value()
                        ], ),
                value = None
            )
        else:
            return V1DeviceCapacity(
                value = None,
        )
        """

    def testV1DeviceCapacity(self):
        """Test V1DeviceCapacity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
