# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_daemon_set_status import V1DaemonSetStatus

class TestV1DaemonSetStatus(unittest.TestCase):
    """V1DaemonSetStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1DaemonSetStatus:
        """Test V1DaemonSetStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1DaemonSetStatus`
        """
        model = V1DaemonSetStatus()
        if include_optional:
            return V1DaemonSetStatus(
                collision_count = 56,
                conditions = [
                    null
                    ],
                current_number_scheduled = 56,
                desired_number_scheduled = 56,
                number_available = 56,
                number_misscheduled = 56,
                number_ready = 56,
                number_unavailable = 56,
                observed_generation = 56,
                updated_number_scheduled = 56
            )
        else:
            return V1DaemonSetStatus(
                current_number_scheduled = 56,
                desired_number_scheduled = 56,
                number_misscheduled = 56,
                number_ready = 56,
        )
        """

    def testV1DaemonSetStatus(self):
        """Test V1DaemonSetStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
