# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_resource_status import V1ResourceStatus

class TestV1ResourceStatus(unittest.TestCase):
    """V1ResourceStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ResourceStatus:
        """Test V1ResourceStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ResourceStatus`
        """
        model = V1ResourceStatus()
        if include_optional:
            return V1ResourceStatus(
                name = '',
                resources = [
                    null
                    ]
            )
        else:
            return V1ResourceStatus(
                name = '',
        )
        """

    def testV1ResourceStatus(self):
        """Test V1ResourceStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
