# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_validating_admission_policy import V1ValidatingAdmissionPolicy

class TestV1ValidatingAdmissionPolicy(unittest.TestCase):
    """V1ValidatingAdmissionPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ValidatingAdmissionPolicy:
        """Test V1ValidatingAdmissionPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ValidatingAdmissionPolicy`
        """
        model = V1ValidatingAdmissionPolicy()
        if include_optional:
            return V1ValidatingAdmissionPolicy(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v1/validating_admission_policy_spec.v1.ValidatingAdmissionPolicySpec(
                    audit_annotations = [
                        null
                        ], 
                    failure_policy = '', 
                    match_conditions = [
                        null
                        ], 
                    match_constraints = null, 
                    param_kind = null, 
                    validations = [
                        null
                        ], 
                    variables = [
                        null
                        ], ),
                status = kubernetes_asyncio.models.v1/validating_admission_policy_status.v1.ValidatingAdmissionPolicyStatus(
                    conditions = [
                        null
                        ], 
                    observed_generation = 56, 
                    type_checking = null, )
            )
        else:
            return V1ValidatingAdmissionPolicy(
        )
        """

    def testV1ValidatingAdmissionPolicy(self):
        """Test V1ValidatingAdmissionPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
