# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_pod_disruption_budget_spec import V1PodDisruptionBudgetSpec

class TestV1PodDisruptionBudgetSpec(unittest.TestCase):
    """V1PodDisruptionBudgetSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1PodDisruptionBudgetSpec:
        """Test V1PodDisruptionBudgetSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1PodDisruptionBudgetSpec`
        """
        model = V1PodDisruptionBudgetSpec()
        if include_optional:
            return V1PodDisruptionBudgetSpec(
                max_unavailable = None,
                min_available = None,
                selector = kubernetes_asyncio_pydantic.models.v1/label_selector.v1.LabelSelector(
                    match_expressions = [
                        null
                        ], 
                    match_labels = {
                        'key' : ''
                        }, ),
                unhealthy_pod_eviction_policy = ''
            )
        else:
            return V1PodDisruptionBudgetSpec(
        )
        """

    def testV1PodDisruptionBudgetSpec(self):
        """Test V1PodDisruptionBudgetSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
