# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_node import V1Node

class TestV1Node(unittest.TestCase):
    """V1Node unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1Node:
        """Test V1Node
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1Node`
        """
        model = V1Node()
        if include_optional:
            return V1Node(
                api_version = '',
                kind = '',
                metadata = kubernetes_asyncio.models.v1/object_meta.v1.ObjectMeta(
                    annotations = {
                        'key' : ''
                        }, 
                    creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deletion_grace_period_seconds = 56, 
                    deletion_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    finalizers = [
                        ''
                        ], 
                    generate_name = '', 
                    generation = 56, 
                    labels = {
                        'key' : ''
                        }, 
                    managed_fields = [
                        null
                        ], 
                    name = '', 
                    namespace = '', 
                    owner_references = [
                        null
                        ], 
                    resource_version = '', 
                    self_link = '', 
                    uid = '', ),
                spec = kubernetes_asyncio.models.v1/node_spec.v1.NodeSpec(
                    config_source = null, 
                    external_id = '', 
                    pod_cidr = '', 
                    pod_cidrs = [
                        ''
                        ], 
                    provider_id = '', 
                    taints = [
                        null
                        ], 
                    unschedulable = True, ),
                status = kubernetes_asyncio.models.v1/node_status.v1.NodeStatus(
                    addresses = [
                        null
                        ], 
                    allocatable = {
                        'key' : kubernetes_asyncio.models.v1_pod_spec_overhead_value.v1_PodSpec_overhead_value()
                        }, 
                    capacity = {
                        'key' : kubernetes_asyncio.models.v1_pod_spec_overhead_value.v1_PodSpec_overhead_value()
                        }, 
                    conditions = [
                        null
                        ], 
                    config = null, 
                    daemon_endpoints = null, 
                    features = null, 
                    images = [
                        null
                        ], 
                    node_info = null, 
                    phase = '', 
                    runtime_handlers = [
                        null
                        ], 
                    volumes_attached = [
                        null
                        ], 
                    volumes_in_use = [
                        ''
                        ], )
            )
        else:
            return V1Node(
        )
        """

    def testV1Node(self):
        """Test V1Node"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
