# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_service_reference2 import V1ServiceReference2

class TestV1ServiceReference2(unittest.TestCase):
    """V1ServiceReference2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1ServiceReference2:
        """Test V1ServiceReference2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1ServiceReference2`
        """
        model = V1ServiceReference2()
        if include_optional:
            return V1ServiceReference2(
                name = '',
                namespace = '',
                port = 56
            )
        else:
            return V1ServiceReference2(
        )
        """

    def testV1ServiceReference2(self):
        """Test V1ServiceReference2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
