# coding: utf-8

"""
    Kubernetes

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: master
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.client.models.v1alpha1_apply_configuration import V1alpha1ApplyConfiguration

class TestV1alpha1ApplyConfiguration(unittest.TestCase):
    """V1alpha1ApplyConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alpha1ApplyConfiguration:
        """Test V1alpha1ApplyConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alpha1ApplyConfiguration`
        """
        model = V1alpha1ApplyConfiguration()
        if include_optional:
            return V1alpha1ApplyConfiguration(
                expression = ''
            )
        else:
            return V1alpha1ApplyConfiguration(
        )
        """

    def testV1alpha1ApplyConfiguration(self):
        """Test V1alpha1ApplyConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
