# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_field_selector_attributes import V1FieldSelectorAttributes

class TestV1FieldSelectorAttributes(unittest.TestCase):
    """V1FieldSelectorAttributes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FieldSelectorAttributes:
        """Test V1FieldSelectorAttributes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FieldSelectorAttributes`
        """
        model = V1FieldSelectorAttributes()
        if include_optional:
            return V1FieldSelectorAttributes(
                raw_selector = '',
                requirements = [
                    null
                    ]
            )
        else:
            return V1FieldSelectorAttributes(
        )
        """

    def testV1FieldSelectorAttributes(self):
        """Test V1FieldSelectorAttributes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
