# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_network_device_data import V1NetworkDeviceData

class TestV1NetworkDeviceData(unittest.TestCase):
    """V1NetworkDeviceData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1NetworkDeviceData:
        """Test V1NetworkDeviceData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1NetworkDeviceData`
        """
        model = V1NetworkDeviceData()
        if include_optional:
            return V1NetworkDeviceData(
                hardware_address = '',
                interface_name = '',
                ips = [
                    ''
                    ]
            )
        else:
            return V1NetworkDeviceData(
        )
        """

    def testV1NetworkDeviceData(self):
        """Test V1NetworkDeviceData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
