# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio_pydantic.models.v1_certificate_signing_request_status import V1CertificateSigningRequestStatus

class TestV1CertificateSigningRequestStatus(unittest.TestCase):
    """V1CertificateSigningRequestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1CertificateSigningRequestStatus:
        """Test V1CertificateSigningRequestStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1CertificateSigningRequestStatus`
        """
        model = V1CertificateSigningRequestStatus()
        if include_optional:
            return V1CertificateSigningRequestStatus(
                certificate = 'YQ==',
                conditions = [
                    null
                    ]
            )
        else:
            return V1CertificateSigningRequestStatus(
        )
        """

    def testV1CertificateSigningRequestStatus(self):
        """Test V1CertificateSigningRequestStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
