# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from kubernetes_asyncio.models.v1_affinity import V1Affinity

class TestV1Affinity(unittest.TestCase):
    """V1Affinity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1Affinity:
        """Test V1Affinity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1Affinity`
        """
        model = V1Affinity()
        if include_optional:
            return V1Affinity(
                node_affinity = kubernetes_asyncio.models.v1/node_affinity.v1.NodeAffinity(
                    preferred_during_scheduling_ignored_during_execution = [
                        null
                        ], 
                    required_during_scheduling_ignored_during_execution = null, ),
                pod_affinity = kubernetes_asyncio.models.v1/pod_affinity.v1.PodAffinity(
                    preferred_during_scheduling_ignored_during_execution = [
                        null
                        ], 
                    required_during_scheduling_ignored_during_execution = [
                        null
                        ], ),
                pod_anti_affinity = kubernetes_asyncio.models.v1/pod_anti_affinity.v1.PodAntiAffinity(
                    preferred_during_scheduling_ignored_during_execution = [
                        null
                        ], 
                    required_during_scheduling_ignored_during_execution = [
                        null
                        ], )
            )
        else:
            return V1Affinity(
        )
        """

    def testV1Affinity(self):
        """Test V1Affinity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
